/* Generated by Yosys 0.54 (git sha1 db72ec3bde296a9512b2d1e6fabf81cfb07c2c1b, clang++ 19.1.7 -fPIC -O3) */

(* top =  1  *)
(* src = "src/adder8.sv:8.8" *)
module adder8(clk_i, rst_ni, a_i, b_i, sum_o, carry_o);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  (* src = "src/adder8.sv:15.22" *)
  wire _032_;
  (* src = "src/adder8.sv:15.22" *)
  wire _033_;
  (* src = "src/adder8.sv:15.22" *)
  wire _034_;
  (* src = "src/adder8.sv:15.22" *)
  wire _035_;
  (* src = "src/adder8.sv:15.22" *)
  wire _036_;
  (* src = "src/adder8.sv:15.22" *)
  wire _037_;
  (* src = "src/adder8.sv:15.22" *)
  wire _038_;
  (* src = "src/adder8.sv:15.22" *)
  wire _039_;
  (* src = "src/adder8.sv:16.22" *)
  wire _040_;
  (* src = "src/adder8.sv:16.22" *)
  wire _041_;
  (* src = "src/adder8.sv:16.22" *)
  wire _042_;
  (* src = "src/adder8.sv:16.22" *)
  wire _043_;
  (* src = "src/adder8.sv:16.22" *)
  wire _044_;
  (* src = "src/adder8.sv:16.22" *)
  wire _045_;
  (* src = "src/adder8.sv:16.22" *)
  wire _046_;
  (* src = "src/adder8.sv:16.22" *)
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  (* src = "src/adder8.sv:22.15" *)
  wire _074_;
  (* src = "src/adder8.sv:22.15" *)
  wire _075_;
  (* src = "src/adder8.sv:22.15" *)
  wire _076_;
  (* src = "src/adder8.sv:22.15" *)
  wire _077_;
  (* src = "src/adder8.sv:22.15" *)
  wire _078_;
  (* src = "src/adder8.sv:22.15" *)
  wire _079_;
  (* src = "src/adder8.sv:22.15" *)
  wire _080_;
  (* src = "src/adder8.sv:22.15" *)
  wire _081_;
  (* hdlname = "a_i" *)
  (* src = "src/adder8.sv:15.22" *)
  input [7:0] a_i;
  wire [7:0] a_i;
  (* hdlname = "b_i" *)
  (* src = "src/adder8.sv:16.22" *)
  input [7:0] b_i;
  wire [7:0] b_i;
  (* hdlname = "carry_d" *)
  (* src = "src/adder8.sv:23.15" *)
  wire carry_d;
  (* hdlname = "carry_o" *)
  (* src = "src/adder8.sv:19.22" *)
  output carry_o;
  wire carry_o;
  (* hdlname = "carry_q" *)
  (* src = "src/adder8.sv:23.24" *)
  wire carry_q;
  (* hdlname = "clk_i" *)
  (* src = "src/adder8.sv:10.22" *)
  input clk_i;
  wire clk_i;
  (* hdlname = "rst_ni" *)
  (* src = "src/adder8.sv:12.22" *)
  input rst_ni;
  wire rst_ni;
  (* hdlname = "sum_d" *)
  (* src = "src/adder8.sv:22.15" *)
  wire [7:0] sum_d;
  (* hdlname = "sum_o" *)
  (* src = "src/adder8.sv:18.22" *)
  output [7:0] sum_o;
  wire [7:0] sum_o;
  (* hdlname = "sum_q" *)
  (* src = "src/adder8.sv:22.24" *)
  wire [7:0] sum_q;
  (* hdlname = "temp_result" *)
  (* src = "src/adder8.sv:26.15" *)
  wire [7:0] temp_result;
  sg13g2_nand2_1 _082_ (
    .A(_037_),
    .B(_045_),
    .Y(_048_)
  );
  sg13g2_and2_1 _083_ (
    .A(_036_),
    .B(_044_),
    .X(_049_)
  );
  sg13g2_or2_1 _084_ (
    .A(_036_),
    .B(_044_),
    .X(_050_)
  );
  sg13g2_nand2b_1 _085_ (
    .A_N(_049_),
    .B(_050_),
    .Y(_051_)
  );
  sg13g2_nand2_1 _086_ (
    .A(_035_),
    .B(_043_),
    .Y(_052_)
  );
  sg13g2_and2_1 _087_ (
    .A(_034_),
    .B(_042_),
    .X(_053_)
  );
  sg13g2_or2_1 _088_ (
    .A(_034_),
    .B(_042_),
    .X(_054_)
  );
  sg13g2_nand2b_1 _089_ (
    .A_N(_053_),
    .B(_054_),
    .Y(_055_)
  );
  sg13g2_nand2_1 _090_ (
    .A(_033_),
    .B(_041_),
    .Y(_056_)
  );
  sg13g2_nand2_1 _091_ (
    .A(_032_),
    .B(_040_),
    .Y(_057_)
  );
  sg13g2_nor2_1 _092_ (
    .A(_033_),
    .B(_041_),
    .Y(_058_)
  );
  sg13g2_xor2_1 _093_ (
    .A(_033_),
    .B(_041_),
    .X(_059_)
  );
  sg13g2_o21ai_1 _094_ (
    .A1(_057_),
    .A2(_058_),
    .B1(_056_),
    .Y(_060_)
  );
  sg13g2_a21oi_1 _095_ (
    .A1(_054_),
    .A2(_060_),
    .B1(_053_),
    .Y(_061_)
  );
  sg13g2_nor2_1 _096_ (
    .A(_035_),
    .B(_043_),
    .Y(_062_)
  );
  sg13g2_xor2_1 _097_ (
    .A(_035_),
    .B(_043_),
    .X(_063_)
  );
  sg13g2_o21ai_1 _098_ (
    .A1(_061_),
    .A2(_062_),
    .B1(_052_),
    .Y(_064_)
  );
  sg13g2_a21oi_1 _099_ (
    .A1(_050_),
    .A2(_064_),
    .B1(_049_),
    .Y(_065_)
  );
  sg13g2_nor2_1 _100_ (
    .A(_037_),
    .B(_045_),
    .Y(_066_)
  );
  sg13g2_xor2_1 _101_ (
    .A(_037_),
    .B(_045_),
    .X(_067_)
  );
  sg13g2_o21ai_1 _102_ (
    .A1(_065_),
    .A2(_066_),
    .B1(_048_),
    .Y(_068_)
  );
  sg13g2_and2_1 _103_ (
    .A(_038_),
    .B(_046_),
    .X(_069_)
  );
  sg13g2_or2_1 _104_ (
    .A(_038_),
    .B(_046_),
    .X(_070_)
  );
  sg13g2_nand2b_1 _105_ (
    .A_N(_069_),
    .B(_070_),
    .Y(_071_)
  );
  sg13g2_xnor2_1 _106_ (
    .A(_068_),
    .B(_071_),
    .Y(_080_)
  );
  sg13g2_a21oi_1 _107_ (
    .A1(_068_),
    .A2(_070_),
    .B1(_069_),
    .Y(_072_)
  );
  sg13g2_xor2_1 _108_ (
    .A(_039_),
    .B(_047_),
    .X(_073_)
  );
  sg13g2_xnor2_1 _109_ (
    .A(_072_),
    .B(_073_),
    .Y(_081_)
  );
  sg13g2_xor2_1 _110_ (
    .A(_032_),
    .B(_040_),
    .X(_074_)
  );
  sg13g2_xnor2_1 _111_ (
    .A(_057_),
    .B(_059_),
    .Y(_075_)
  );
  sg13g2_xnor2_1 _112_ (
    .A(_055_),
    .B(_060_),
    .Y(_076_)
  );
  sg13g2_xnor2_1 _113_ (
    .A(_061_),
    .B(_063_),
    .Y(_077_)
  );
  sg13g2_xnor2_1 _114_ (
    .A(_051_),
    .B(_064_),
    .Y(_078_)
  );
  sg13g2_xnor2_1 _115_ (
    .A(_065_),
    .B(_067_),
    .Y(_079_)
  );
  (* src = "src/adder8.sv:32.3" *)
  sg13g2_dfrbpq_1 _116_ (
    .CLK(clk_i),
    .D(sum_d[0]),
    .Q(sum_q[0]),
    .RESET_B(rst_ni)
  );
  (* src = "src/adder8.sv:32.3" *)
  sg13g2_dfrbpq_1 _117_ (
    .CLK(clk_i),
    .D(sum_d[1]),
    .Q(sum_q[1]),
    .RESET_B(rst_ni)
  );
  (* src = "src/adder8.sv:32.3" *)
  sg13g2_dfrbpq_1 _118_ (
    .CLK(clk_i),
    .D(sum_d[2]),
    .Q(sum_q[2]),
    .RESET_B(rst_ni)
  );
  (* src = "src/adder8.sv:32.3" *)
  sg13g2_dfrbpq_1 _119_ (
    .CLK(clk_i),
    .D(sum_d[3]),
    .Q(sum_q[3]),
    .RESET_B(rst_ni)
  );
  (* src = "src/adder8.sv:32.3" *)
  sg13g2_dfrbpq_1 _120_ (
    .CLK(clk_i),
    .D(sum_d[4]),
    .Q(sum_q[4]),
    .RESET_B(rst_ni)
  );
  (* src = "src/adder8.sv:32.3" *)
  sg13g2_dfrbpq_1 _121_ (
    .CLK(clk_i),
    .D(sum_d[5]),
    .Q(sum_q[5]),
    .RESET_B(rst_ni)
  );
  (* src = "src/adder8.sv:32.3" *)
  sg13g2_dfrbpq_1 _122_ (
    .CLK(clk_i),
    .D(sum_d[6]),
    .Q(sum_q[6]),
    .RESET_B(rst_ni)
  );
  (* src = "src/adder8.sv:32.3" *)
  sg13g2_dfrbpq_1 _123_ (
    .CLK(clk_i),
    .D(sum_d[7]),
    .Q(sum_q[7]),
    .RESET_B(rst_ni)
  );
  assign carry_d = 1'h0;
  assign carry_o = 1'h0;
  assign carry_q = 1'h0;
  assign sum_o = sum_q;
  assign temp_result = sum_d;
  assign _037_ = a_i[5];
  assign _045_ = b_i[5];
  assign _036_ = a_i[4];
  assign _044_ = b_i[4];
  assign _035_ = a_i[3];
  assign _043_ = b_i[3];
  assign _034_ = a_i[2];
  assign _042_ = b_i[2];
  assign _033_ = a_i[1];
  assign _041_ = b_i[1];
  assign _032_ = a_i[0];
  assign _040_ = b_i[0];
  assign sum_d[6] = _080_;
  assign _039_ = a_i[7];
  assign _047_ = b_i[7];
  assign _038_ = a_i[6];
  assign _046_ = b_i[6];
  assign sum_d[7] = _081_;
  assign sum_d[0] = _074_;
  assign sum_d[1] = _075_;
  assign sum_d[2] = _076_;
  assign sum_d[3] = _077_;
  assign sum_d[4] = _078_;
  assign sum_d[5] = _079_;
endmodule
